// ═══════════════════════════════════════════════════════════════
// RCC-HIROS — Permission sets per role
// Single source of truth for built-in role → permission grants.
// Imported by prisma/seed.ts and scripts/sync-permissions.ts.
// Keep in sync with src/lib/permissions.ts (ALL_PERMISSIONS).
// ═══════════════════════════════════════════════════════════════

export const ALL_PERMISSIONS = [
  "dashboard.view",
  "profiling.view",
  "profiling.view_inactive",
  "profiling.create",
  "profiling.edit",
  "profiling.editIdentity",
  "profiling.editEmployment",
  "profiling.editSalary",
  "profiling.editStatus",
  "profiling.delete",
  "profile.selfEdit",
  "profile.editAll",
  "attendance.view",
  "attendance.clock_in",
  "attendance.edit",
  "attendance.edit_on_premise",
  "attendance.view_all",
  "evaluation.view",
  "evaluation.submit",
  "evaluation.view_results",
  "evaluation.manage_forms",
  "evaluation.reset",
  "leave.request",
  "leave.approve_l1",
  "leave.approve_l2",
  "leave.view_all",
  "leave.manage_types",
  "reports.view",
  "reports.export",
  "fpass.fill",
  "fpass.manage",
  "roles.view",
  "roles.create",
  "roles.edit",
  "roles.delete",
  "groups.view",
  "groups.create",
  "groups.edit",
  "groups.delete",
  "biometric.enroll",
  "biometric.manage",
];

export const ACCOUNTANT_PERMS = [
  "dashboard.view",
  "profiling.view",
  "profiling.view_inactive",
  "profile.selfEdit",
  "profile.editAll",
  "attendance.view",
  "attendance.clock_in",
  "attendance.edit",
  "attendance.edit_on_premise",
  "leave.request",
  "leave.approve_l2",
  "leave.view_all",
  "reports.view",
  "reports.export",
  "groups.view",
  "roles.view",
  "biometric.enroll",
];

export const HR_PERMS = [
  "dashboard.view",
  "profiling.view",
  "profiling.view_inactive",
  "profiling.create",
  "profiling.edit",
  "profiling.editIdentity",
  "profiling.editEmployment",
  "profiling.editStatus",
  "profile.selfEdit",
  "profile.editAll",
  "attendance.view",
  "attendance.clock_in",
  "attendance.edit",
  "attendance.edit_on_premise",
  "evaluation.view",
  "evaluation.submit",
  "evaluation.manage_forms",
  "evaluation.reset",
  "leave.request",
  "leave.approve_l2",
  "leave.view_all",
  "leave.manage_types",
  "reports.view",
  "reports.export",
  "fpass.fill",
  "fpass.manage",
  "groups.view",
  "groups.create",
  "groups.edit",
  "groups.delete",
  "roles.view",
  "biometric.enroll",
  "biometric.manage",
];

export const DEAN_PERMS = [
  "dashboard.view",
  "profiling.view",
  "profile.selfEdit",
  "attendance.view",
  "attendance.clock_in",
  "evaluation.view",
  "evaluation.submit",
  "leave.approve_l1",
  "leave.request",
  "reports.view",
  "fpass.fill",
  "groups.view",
];

export const IT_STAFF_PERMS = [
  "dashboard.view",
  "profiling.view",
  "profiling.view_inactive",
  "profiling.create",
  "profiling.edit",
  "profiling.editIdentity",
  "profiling.editEmployment",
  "profile.selfEdit",
  "profile.editAll",
  "attendance.view",
  "attendance.clock_in",
  "attendance.edit",
  "attendance.edit_on_premise",
  "evaluation.view",
  "evaluation.manage_forms",
  "leave.view_all",
  "evaluation.reset",
  "leave.manage_types",
  "reports.view",
  "reports.export",
  "fpass.fill",
  "fpass.manage",
  "roles.view",
  "roles.create",
  "roles.edit",
  "groups.view",
  "groups.create",
  "groups.edit",
  "groups.delete",
  "biometric.enroll",
  "biometric.manage",
];

export const PROFESSOR_PERMS = [
  "dashboard.view",
  "attendance.clock_in",
  "attendance.view",
  "leave.request",
  "evaluation.view_results",
  "fpass.fill",
  "profile.selfEdit",
];

export const HR_ASSISTANT_PERMS = [
  "dashboard.view",
  "profiling.view",
  "profile.selfEdit",
  "attendance.view",
  "attendance.clock_in",
  "evaluation.view",
  "evaluation.view_results",
  "leave.request",
  "reports.view",
  "groups.view",
];

/** Built-in role name → permission grant array. */
export const ROLE_PERMISSION_SETS: Record<string, readonly string[]> = {
  "System Admin": ALL_PERMISSIONS,
  Accountant: ACCOUNTANT_PERMS,
  "HR Personnel": HR_PERMS,
  Dean: DEAN_PERMS,
  "IT Staff": IT_STAFF_PERMS,
  Professor: PROFESSOR_PERMS,
  "HR Assistant": HR_ASSISTANT_PERMS,
};
