// ═══════════════════════════════════════════════════════════════
// RCC-HIROS — Personnel Fill Seed (session-34)
// Fills ONLY empty personnel fields/sections for all employees:
// scalars, profileData sections, certificates, 2x2 photos, and one
// sample 201-file PDF each. NEVER overwrites existing values — every
// write is guarded by an emptiness check, so reruns are safe.
// Photos: brown initials-placeholder PNGs are generated by
// scripts/make-seed-photos.py (PIL) into uploads/employees/photos;
// this script only links the filenames.
// ═══════════════════════════════════════════════════════════════

import { writeFileSync, mkdirSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { db as prisma } from "../src/lib/db";

const UPLOAD_ROOT = join(process.cwd(), "uploads", "employees");
const PHOTO_ROOT = join(UPLOAD_ROOT, "photos");
const PHOTO_FILE = "seed-2x2.png";

// ── Deterministic invented pools (Angeles City / Pampanga flavor) ──

const ADDRESSES = [
  "123 San Roque, Angeles City, Pampanga",
  "45 Malabanias, Angeles City, Pampanga",
  "78 Cutcut, Angeles City, Pampanga",
  "12 Sta. Trinidad, Angeles City, Pampanga",
  "56 Pampang, Angeles City, Pampanga",
  "90 Balibago, Angeles City, Pampanga",
  "34 Anunas, Angeles City, Pampanga",
  "67 Pulungbulu, Angeles City, Pampanga",
  "23 Sto. Domingo, Angeles City, Pampanga",
  "89 Capaya, Angeles City, Pampanga",
  "15 Dolores, City of San Fernando, Pampanga",
  "41 Sta. Lucia, City of San Fernando, Pampanga",
  "72 San Agustin, City of San Fernando, Pampanga",
  "8 Del Pilar, City of San Fernando, Pampanga",
  "66 San Jose, Angeles City, Pampanga",
  "29 Claro M. Recto, Angeles City, Pampanga",
  "53 Hensonville, Angeles City, Pampanga",
  "77 Villa Dolores, Angeles City, Pampanga",
  "11 Pandan, Angeles City, Pampanga",
  "99 Margot, Angeles City, Pampanga",
];
const BIRTH_PLACES = [
  "Angeles City, Pampanga", "City of San Fernando, Pampanga",
  "Mabalacat City, Pampanga", "Guagua, Pampanga",
  "Apalit, Pampanga", "Tarlac City, Tarlac",
];
const CIVIL = ["Single", "Married", "Single", "Married", "Single"];
const RELIGIONS = ["Roman Catholic", "Roman Catholic", "Born Again Christian", "Iglesia ni Cristo", "Roman Catholic"];
const HEIGHTS = ["5'4\"", "5'6\"", "5'2\"", "5'8\"", "5'5\"", "5'7\""];
const WEIGHTS = ["58 kg", "65 kg", "52 kg", "70 kg", "60 kg", "68 kg"];
const BLOOD = ["O+", "A+", "B+", "O+", "AB+", "O-"];
const BIRTH_YEARS = [1988, 1992, 1985, 1995, 1990, 1982, 1994, 1987, 1991, 1980];

// ── Role-flavored section rows ──

interface Row { [k: string]: string }

function sectionRows(role: string): Record<string, Row[]> {
  const isProfessor = /professor/i.test(role);
  const isDean = /dean/i.test(role);
  const isAccountant = /accountant/i.test(role);
  const isIT = /it staff/i.test(role);
  const isHR = /hr/i.test(role);

  const education: Row[] = isProfessor || isDean
    ? [
        { degree: "Master of Science in Computer Science", dateEarned: "2016", school: "Holy Angel University" },
        { degree: "Bachelor of Science in Information Technology", dateEarned: "2010", school: "Angeles University Foundation" },
      ]
    : isAccountant
      ? [
          { degree: "Bachelor of Science in Accountancy", dateEarned: "2014", school: "Holy Angel University" },
          { degree: "Master in Business Administration (units)", dateEarned: "2019", school: "Angeles University Foundation" },
        ]
      : isIT
        ? [
            { degree: "Bachelor of Science in Information Systems", dateEarned: "2017", school: "Holy Angel University" },
          ]
        : [
            { degree: "Bachelor of Science in Business Administration", dateEarned: "2013", school: "Angeles University Foundation" },
          ];

  const experience: Row[] = isDean
    ? [
        { position: "Dean", year: "2021-present", organization: "Republic Central Colleges" },
        { position: "Program Chair", year: "2016-2021", organization: "Republic Central Colleges" },
      ]
    : [
        { position: role, year: "2019-present", organization: "Republic Central Colleges" },
        { position: isHR ? "HR Clerk" : isAccountant ? "Accounting Staff" : isIT ? "IT Support" : "Instructor", year: "2015-2019", organization: "Systems Plus College Foundation" },
      ];

  const eligibility: Row[] = isAccountant
    ? [{ exam: "Certified Public Accountant Licensure Examination", place: "Manila", date: "2015", rating: "82.40" }]
    : isProfessor || isDean
      ? [{ exam: "Licensure Examination for Professional Teachers", place: "City of San Fernando", date: "2011", rating: "84.60" }]
      : [{ exam: "Civil Service Examination - Professional", place: "City of San Fernando", date: "2014", rating: "83.25" }];

  const awards: Row[] = isDean
    ? [
        { award: "Outstanding Administrator", year: "2024", institution: "Republic Central Colleges" },
        { award: "Service Award (10 years)", year: "2023", institution: "Republic Central Colleges" },
      ]
    : [{ award: "Outstanding Employee", year: "2024", institution: "Republic Central Colleges" }];

  const publications: Row[] = isProfessor || isDean
    ? [{ title: "Modular Learning in IT Education", publication: "RCC Research Journal", issue: "Vol. 4, 2025" }]
    : [];

  const affiliations: Row[] = isProfessor || isDean || isIT
    ? [{ organization: "PSITE Central Luzon", position: "Member", date: "2023-present" }]
    : isAccountant
      ? [{ organization: "PICPA Pampanga Chapter", position: "Member", date: "2022-present" }]
      : [{ organization: " rank-and-file Employees Association", position: "Member", date: "2021-present" }];

  const seminars: Row[] = [
    { title: "CHED Regional Research Colloquium", scope: "Regional", date: "2026", nature: "Participant" },
    { title: "In-House Pedagogy Retooling", scope: "Institutional", date: "2025", nature: isProfessor || isDean ? "Paper Presenter" : "Participant" },
  ];

  const accomplishments: Row[] = isDean
    ? [{ function: "Foundation Anniversary", nature: "Working Committee Head" }]
    : [{ function: "Foundation Anniversary", nature: "Working Committee" }];

  const community: Row[] = [
    { title: "Brigada Eskwela", beneficiaries: "Sta. Maria Elementary School", date: "2025", nature: "Volunteer" },
  ];

  return { education, experience, eligibility, awards, publications, affiliations, seminars, accomplishments, community };
}

function certRows(role: string): Array<{ title: string; issuer: string | null; certificateNo: string | null; issueDate: Date | null }> {
  if (/accountant/i.test(role)) {
    return [{ title: "CPA Certificate of Registration", issuer: "Professional Regulation Commission", certificateNo: null, issueDate: new Date("2015-11-02") }];
  }
  if (/professor|dean/i.test(role)) {
    return [{ title: "CHED Faculty Development Certificate", issuer: "Commission on Higher Education", certificateNo: null, issueDate: new Date("2022-05-20") }];
  }
  if (/it staff/i.test(role)) {
    return [{ title: "TESDA NC II - Computer Systems Servicing", issuer: "TESDA", certificateNo: null, issueDate: new Date("2019-08-15") }];
  }
  return [{ title: "Civil Service Eligibility Certificate", issuer: "Civil Service Commission", certificateNo: null, issueDate: new Date("2014-09-01") }];
}

// ── Minimal one-page sample PDF (hand-built, no deps) ──

function samplePdf(name: string, employeeCode: string): Buffer {
  const text = `201 File - Sample Document - ${name} (${employeeCode})`;
  const content = `BT /F1 14 Tf 72 720 Td (201 File - Sample Document) Tj ET\nBT /F1 11 Tf 72 700 Td (${text}) Tj ET\nBT /F1 11 Tf 72 684 Td (Placeholder portfolio file seeded for print/export verification.) Tj ET\n`;
  const objs = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${content.length} >>\nstream\n${content}endstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objs.forEach((body, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  for (const o of offsets) pdf += `${String(o).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, "utf-8");
}

// ── Main ──

async function main() {
  const employees = await prisma.employee.findMany({
    where: { active: true },
    select: {
      id: true, employeeId: true, firstName: true, middleName: true, lastName: true,
      gender: true, address: true, birthday: true, placeOfBirth: true,
      rank: true, civilStatus: true, citizenship: true, religion: true,
      height: true, weight: true, bloodType: true, photo: true,
      profileData: true, groupId: true,
      role: { select: { name: true, isSystem: true } },
      certificates: { select: { id: true } },
      files: { select: { id: true } },
    },
    orderBy: { employeeId: "asc" },
  });

  const admin = await prisma.employee.findFirst({
    where: { role: { isSystem: true } },
    select: { id: true },
  });

  let scalars = 0, sections = 0, certs = 0, photos = 0, files = 0;

  for (let i = 0; i < employees.length; i++) {
    const e = employees[i];
    const role = e.role?.name ?? "";
    const fullName = `${e.firstName} ${e.middleName ? e.middleName + " " : ""}${e.lastName}`;

    // 1. Scalars — fill empties only
    const data: Record<string, unknown> = {};
    if (!e.address) data.address = ADDRESSES[i % ADDRESSES.length];
    if (!e.birthday) data.birthday = new Date(BIRTH_YEARS[i % BIRTH_YEARS.length], i % 12, (i % 27) + 1);
    if (!e.placeOfBirth) data.placeOfBirth = BIRTH_PLACES[i % BIRTH_PLACES.length];
    if (!e.rank) data.rank = /professor/i.test(role) ? "Assistant Professor II" : /dean/i.test(role) ? "Associate Professor V" : /accountant/i.test(role) ? "Accountant II" : /it staff/i.test(role) ? "IT Staff" : "Administrative Aide IV";
    if (!e.civilStatus) data.civilStatus = CIVIL[i % CIVIL.length];
    if (!e.citizenship) data.citizenship = "Filipino";
    if (!e.religion) data.religion = RELIGIONS[i % RELIGIONS.length];
    if (!e.height) data.height = HEIGHTS[i % HEIGHTS.length];
    if (!e.weight) data.weight = WEIGHTS[i % WEIGHTS.length];
    if (!e.bloodType) data.bloodType = BLOOD[i % BLOOD.length];
    if (Object.keys(data).length > 0) {
      await prisma.employee.update({ where: { id: e.id }, data });
      scalars += Object.keys(data).length;
    }

    // 2. profileData sections — fill empty sections only
    let parsed: Record<string, Row[]> = {};
    try { parsed = e.profileData ? (JSON.parse(e.profileData) as Record<string, Row[]>) : {}; } catch { parsed = {}; }
    const wanted = sectionRows(role);
    let changed = false;
    for (const [key, rows] of Object.entries(wanted)) {
      if ((!parsed[key] || parsed[key].length === 0) && rows.length > 0) {
        parsed[key] = rows;
        changed = true;
        sections++;
      }
    }
    if (changed) {
      await prisma.employee.update({ where: { id: e.id }, data: { profileData: JSON.stringify(parsed) } });
    }

    // 3. Certificates — add only when none
    if (e.certificates.length === 0) {
      for (const c of certRows(role)) {
        await prisma.employeeCertificate.create({
          data: { employeeId: e.id, title: c.title, issuer: c.issuer, certificateNo: c.certificateNo, issueDate: c.issueDate },
        });
        certs++;
      }
    }

    // 4. Photo — link placeholder written by scripts/make-seed-photos.py
    if (!e.photo) {
      const dir = join(PHOTO_ROOT, e.id);
      const file = join(dir, PHOTO_FILE);
      if (existsSync(file) && statSync(file).size > 100) {
        await prisma.employee.update({ where: { id: e.id }, data: { photo: PHOTO_FILE } });
        photos++;
      } else {
        console.warn(`[seed-personnel] photo missing for ${e.employeeId} — run scripts/make-seed-photos.py first`);
      }
    }

    // 5. One sample 201-file PDF — only when the employee has no files
    if (e.files.length === 0) {
      const dir = join(UPLOAD_ROOT, e.id);
      mkdirSync(dir, { recursive: true });
      const fileName = "201-file-sample.pdf";
      writeFileSync(join(dir, fileName), samplePdf(fullName, e.employeeId));
      await prisma.employeeFile.create({
        data: {
          employeeId: e.id,
          fileName,
          originalName: "201 File - Sample.pdf",
          mimeType: "application/pdf",
          fileSize: statSync(join(dir, fileName)).size,
          description: "Seeded sample 201-file document",
          uploadedById: admin?.id ?? null,
        },
      });
      files++;
    }
  }

  console.log(`[seed-personnel] done: ${employees.length} employees | scalar fields filled=${scalars} | sections filled=${sections} | certificates added=${certs} | photos linked=${photos} | sample files added=${files}`);
}

main()
  .catch((err) => { console.error("[seed-personnel] FAILED:", err); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
